/*
 * Copyright (C) 2023 by Rodrigo Antonio de Araujo
 */
#include <map>
#include "components/xpm/xpm.h"

#pragma GCC diagnostic push
// there is no problem, i dont use it as a char *, i do as const char*
// i'd rather not modify .xpm files because it's generated by gimp and i keep it as it is.
#pragma GCC diagnostic ignored "-Wwrite-strings"

#include "components/xpm/data/24x24/new.xpm"
#include "components/xpm/data/24x24/door.xpm"
#include "components/xpm/data/24x24/exit.xpm"
#include "components/xpm/data/24x24/component.xpm"
#include "components/xpm/data/24x24/close.xpm"
#include "components/xpm/data/24x24/computer.xpm"
#include "components/xpm/data/24x24/remove.xpm"
#include "components/xpm/data/24x24/erase.xpm"


#pragma GCC diagnostic pop

namespace dfe {
namespace xpm {

std::map<xpm_t, const char * const*> xpm_db = {
    { img_24x24_exit, xpm_exit },
    { img_24x24_new, xpm_new },
    { img_24x24_open_layer, xpm_component},
    { img_24x24_close, xpm_close},
    { img_24x24_open, xpm_door },
    { img_24x24_settings, xpm_computer },
    { img_24x24_remove_layer, xpm_remove },
    { img_24x24_remove_all_layers, xpm_erase},
};

std::shared_ptr<Fl_RGB_Image> image(xpm_t xpm_id, Fl_Color bg) {
    Fl_Pixmap image(xpm_db[xpm_id]);
    return std::shared_ptr<Fl_RGB_Image>(new Fl_RGB_Image(&image, bg));
}

} // namespace xpm
}  // namespace vcutter
